4 TO - DO - Task

Please complete all the problem listed below.

4.1 Exercise on Functions:

Task - 1:

Create a Python program that converts between different units of measurement.

• The program should:

1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).

2. Ask the user to input the value to be converted.

3. Perform the conversion and display the result.

4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:

1. Functions: Define at least one function to perform the conversion.

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).

3. User Input: Prompt the user to select the conversion type and input the value.

4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:

1. Length:

– Convert meters (m) to feet (ft).

– Convert feet (ft) to meters (m).

2. Weight:

– Convert kilograms (kg) to pounds (lbs).

– Convert pounds (lbs) to kilograms (kg).

3. Volume:

– Convert liters (L) to gallons (gal).

– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units(conversion_type, value):

    if conversion_type == 1:
        return value * 3.28084
    elif conversion_type == 2:
        return value / 3.28084
    elif conversion_type == 3:
        return value * 2.20462
    elif conversion_type == 4:
        return value / 2.20462
    elif conversion_type == 5:
        return value * 0.264172
    elif conversion_type == 6:
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Choose conversion type (1-6): "))
        value = float(input("Enter the value to convert: "))

        result = convert_units(choice, value)

        if result is None:
            print("Invalid conversion type selected.")
        else:
            print("Converted value:", result)

    except ValueError:
        print("Error: Please enter a valid numeric value.")

main()

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 4
Enter the value to convert: 2
Converted value: 0.9071858188712795


Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).

2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.

4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).

3. User Input: Prompt the user to select the operation and input the list of numbers.

4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

def main():
    print("List Operations Program")
    print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")

    try:
        choice = int(input("Select an operation (1-4): "))
        user_input = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in user_input.split()]

        if len(numbers) == 0:
            print("Error: The list is empty.")
            return

        if choice == 1:
            print("Sum =", calculate_sum(numbers))
        elif choice == 2:
            print("Average =", calculate_average(numbers))
        elif choice == 3:
            print("Maximum =", find_maximum(numbers))
        elif choice == 4:
            print("Minimum =", find_minimum(numbers))
        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numeric values.")

main()

List Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum
Select an operation (1-4): 3
Enter numbers separated by spaces: 2
Maximum = 2.0


4.2 Exercise on List Manipulation:

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [4]:
def extract_every_other(lst):
    return lst[::2]

def main():
    user_input = input("Enter elements of the list separated by spaces: ")
    lst = [int(x) for x in user_input.split()]
    result = extract_every_other(lst)
    print("Every other element:", result)

main()

Enter elements of the list separated by spaces: 1 2 3 4 5 6
Every other element: [1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [8]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

def main():
    user_input = input("Enter elements of the list separated by spaces: ")
    lst = [int(x) for x in user_input.split()]
    start = int(input("Enter start index: "))
    end = int(input("Enter end index: "))
    result = get_sublist(lst, start, end)
    print("Sublist:", result)

main()

Enter elements of the list separated by spaces: 1 2 3 4 5 6
Enter start index: 2
Enter end index: 4
Sublist: [3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [9]:
def reverse_list(lst):
    return lst[::-1]

def main():
    user_input = input("Enter elements of the list (e.g., 1 2 3 4 5 or [1,2,3,4,5]): ")

    # Detect if input contains brackets
    if "[" in user_input and "]" in user_input:
        cleaned = user_input.strip("[]").replace(" ", "")
        lst = [int(x) for x in cleaned.split(",")]
    else:
        lst = [int(x) for x in user_input.split()]

    result = reverse_list(lst)
    print("Reversed list:", result)

main()

Enter elements of the list (e.g., 1 2 3 4 5 or [1,2,3,4,5]): 1 2 3 4 5
Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [6]:
def remove_first_last(lst):
    return lst[1:-1]

def main():
    user_input = input("Enter elements of the list (e.g., 1 2 3 4 5 or [1,2,3,4,5]): ")

    if "[" in user_input and "]" in user_input:
        cleaned = user_input.strip("[]").replace(" ", "")
        lst = [int(x) for x in cleaned.split(",")]
    else:
        lst = [int(x) for x in user_input.split()]

    result = remove_first_last(lst)
    print("List without first and last elements:", result)

main()

Enter elements of the list (e.g., 1 2 3 4 5 or [1,2,3,4,5]): 1 2 3 4 5
List without first and last elements: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [7]:
def get_first_n(lst, n):
    return lst[:n]

def main():
    user_input = input("Enter elements of the list (e.g., 1 2 3 4 5 or [1,2,3,4,5]): ")

    if "[" in user_input and "]" in user_input:
        cleaned = user_input.strip("[]").replace(" ", "")
        lst = [int(x) for x in cleaned.split(",")]
    else:
        lst = [int(x) for x in user_input.split()]

    n = int(input("Enter the number of elements to extract: "))
    result = get_first_n(lst, n)
    print("First", n, "elements:", result)

main()

Enter elements of the list (e.g., 1 2 3 4 5 or [1,2,3,4,5]): 1 2 3 4 5
Enter the number of elements to extract: 3
First 3 elements: [1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [1]:
def get_last_n(lst, n):
    return lst[-n:]

def main():
    user_input = input("Enter elements of the list (e.g., 1 2 3 4 5 or [1,2,3,4,5]): ")

    if "[" in user_input and "]" in user_input:
        cleaned = user_input.strip("[]").replace(" ", "")
        lst = [int(x) for x in cleaned.split(",")]
    else:
        lst = [int(x) for x in user_input.split()]

    n = int(input("Enter the number of elements to extract from the end: "))
    result = get_last_n(lst, n)
    print("Last", n, "elements:", result)

main()

Enter elements of the list (e.g., 1 2 3 4 5 or [1,2,3,4,5]): [1, 2, 3, 4, 5]
Enter the number of elements to extract from the end: 2
Last 2 elements: [4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [10]:
def reverse_skip(lst):
    return lst[-2::-2]

def main():
    user_input = input("Enter elements of the list (e.g., 1 2 3 4 5 6 or [1,2,3,4,5,6]): ")

    if "[" in user_input and "]" in user_input:
        cleaned = user_input.strip("[]").replace(" ", "")
        lst = [int(x) for x in cleaned.split(",")]
    else:
        lst = [int(x) for x in user_input.split()]

    result = reverse_skip(lst)
    print("Result:", result)

main()

Enter elements of the list (e.g., 1 2 3 4 5 6 or [1,2,3,4,5,6]): [1, 2, 3, 4, 5, 6]
Result: [5, 3, 1]


4.3 Exercise on Nested List:

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [11]:
def flatten(lst):
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

def main():
    user_input = input("Enter a nested list (e.g., [[1,2],[3,4],[5]]): ")
    nested_list = eval(user_input)
    result = flatten(nested_list)
    print("Flattened list:", result)

main()

Enter a nested list (e.g., [[1,2],[3,4],[5]]): [[1,2],[3,4],[5]]
Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [12]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

def main():
    user_input = input("Enter a nested list (e.g., [[1,2,3],[4,5,6],[7,8,9]]): ")
    lst = eval(user_input)

    index_input = input("Enter indices separated by spaces (e.g., 1 2): ")
    indices = [int(i) for i in index_input.split()]

    result = access_nested_element(lst, indices)
    print("Element:", result)

main()

Enter a nested list (e.g., [[1,2,3],[4,5,6],[7,8,9]]): [[1,2,3],[4,5,6],[7,8,9]]
Enter indices separated by spaces (e.g., 1 2): 1 2
Element: 6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [13]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def main():
    user_input = input("Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): ")
    lst = eval(user_input)
    result = sum_nested(lst)
    print("Sum:", result)

main()

Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): [[1, 2], [3, [4, 5]], 6]
Sum: 21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [14]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)
    return result

def main():
    user_input = input("Enter a nested list (e.g., [[1,2],[3,2],[4,5]]): ")
    lst = eval(user_input)
    elem = int(input("Enter the element to remove: "))
    result = remove_element(lst, elem)
    print("Modified list:", result)

main()

Enter a nested list (e.g., [[1,2],[3,2],[4,5]]): [[1,2],[3,2],[4,5]]
Enter the element to remove: 2
Modified list: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [15]:
def find_max(lst):
    maximum = None
    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
        else:
            value = item
        if maximum is None or value > maximum:
            maximum = value
    return maximum

def main():
    user_input = input("Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): ")
    lst = eval(user_input)
    result = find_max(lst)
    print("Maximum element:", result)

main()

Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): [[1,2],[3,[4,5]],6]
Maximum element: 6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [16]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

def main():
    user_input = input("Enter a nested list (e.g., [[1,2],[2,3],[2,4]]): ")
    lst = eval(user_input)
    elem = int(input("Enter the element to count: "))
    result = count_occurrences(lst, elem)
    print("Occurrences:", result)

main()

Enter a nested list (e.g., [[1,2],[2,3],[2,4]]): [[1,2],[2,3],[2,4]]
Enter the element to count: 2
Occurrences: 3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [17]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

def main():
    user_input = input("Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): ")
    lst = eval(user_input)
    result = deep_flatten(lst)
    print("Flattened list:", result)

main()

Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): [[[1,2],[3,4]],[[5,6],[7,8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [18]:
def average_nested(lst):
    total = 0
    count = 0
    for item in lst:
        if isinstance(item, list):
            s, c = average_nested(item)
            total += s
            count += c
        else:
            total += item
            count += 1
    return total, count

def main():
    user_input = input("Enter a nested list (e.g., [[1,2],[3,4],[5,6]]): ")
    lst = eval(user_input)
    total, count = average_nested(lst)
    avg = total / count
    print("Average:", avg)

main()

Enter a nested list (e.g., [[1,2],[3,4],[5,6]]): [[1,2],[3,4],[5,6]]
Average: 3.5


10 To - Do - NumPy

Please complete all the problems listed below:

10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

Complete the following Tasks:

1. Initialize an empty array with size 2X2.

2. Initialize an all one array with size 4X2.

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [19]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-one 4x2 array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value = 7
shape = (3, 3)
filled_array = np.full(shape, fill_value)
print("\nFilled 3x3 array with value 7:\n", filled_array)

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros array like given array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes array like given array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy array from list [1,2,3,4]:\n", numpy_array)

Empty 2x2 array:
 [[4.73473993e-315 0.00000000e+000]
 [9.88131292e-324             nan]]

All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled 3x3 array with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array like given array:
 [[0 0]
 [0 0]]

Ones array like given array:
 [[1 1]
 [1 1]]

Numpy array from list [1,2,3,4]:
 [1 2 3 4]


Problem - 2: Array Manipulation:
Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

3. Create a 3X3 identity matrix.{Hint:np.eye()}

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

5. Create a 10X10 array with random values and find the minimum and maximum values.

6. Create a zero array of size 10 and replace 5th element with 1.

7. Reverse an array arr = [1,2,0,0,4,0].

8. Create a 2d array with 1 on border and 0 inside.

9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [20]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 matrix from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\nRandom array of size 30:\n", random_array_30)
print("Mean of array:", mean_value)

# 5. Create a 10x10 array with random values and find min & max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nRandom 10x10 array:\n", random_10x10)
print("Minimum:", min_value, "Maximum:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # index 4 is the 5th element
print("\nZero array with 5th element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
size = 5  # example size 5x5
border_array = np.ones((size, size))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 checkerboard pattern:\n", checkerboard)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.5237816  0.77903658 0.46857857 0.81268677 0.48785863 0.40345031
 0.18380184 0.33558491 0.90169559 0.09922224 0.11808122 0.46966836
 0.12582225 0.48309225 0.50253125 0.68999256 0.34974781 0.86294633
 0.8209904  0.99050535 0.76510942 0.23026488 0.88364899 0.05239165
 0.76626544 0.85330389 0.50944143 0.35427541 0.51895506 0.73743555]
Mean of array: 0.5360055502917211

Random 10x10 array:
 [[0.30748279 0.74109516 0.22226231 0.53158522 0.87867654 0.55663905
  0.49657118 0.29297316 0.52690035 0.86539333]
 [0.57491846 0.3944228  0.93113107 0.03406136 0.76190115 0.82808873
  0.32236042 0.44908688 0.74762772 0.61521783]
 [0.40407915 0.90109484 0.62883009 0.41078937 0.89568004 0.80688672
  0.42524146 0.18649941 

Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1. Add the two array.

2. Subtract the two array.

3. Multiply the array with any integers of your choice.

4. Find the square of each element of the array.

5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [21]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("x + y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nx - y:\n", sub_xy)

# 3. Multiply the array with an integer (example: multiply x by 3)
mul_x = x * 3
print("\nx * 3:\n", mul_x)

# 4. Square each element of the array
square_x = x ** 2
print("\nSquare of x:\n", square_x)

# 5. Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product v . w:", dot_vw)
print("Dot product x . v:\n", dot_xv)
print("Dot product x . y:\n", dot_xy)

# 6. Concatenate x and y along rows (axis=0) and v and w along columns (axis=0 for 1D needs reshape)
concat_xy_row = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along rows:\n", concat_xy_row)

# v and w need to be reshaped to column vectors for vertical concatenation
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_vw_col = np.concatenate((v_col, w_col), axis=1)
print("\nConcatenate v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v (will raise error if attempted directly)
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError when concatenating x and v:", e)
    print("Explanation: x is a 2x2 array but v is 1D with 2 elements; their dimensions are incompatible for concatenation along rows.")

x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

x * 3:
 [[ 3  6]
 [ 9 15]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot product v . w: 219
Dot product x . v:
 [29 77]
Dot product x . y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2x2 array but v is 1D with 2 elements; their dimensions are incompatible for concatenation along rows.


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

1. Prove A.A−1 = I.

2. Prove AB ̸= BA.

3. Prove (AB)

T = BTAT

In [22]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^(-1) = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^(-1) =\n", identity)

# Verify it is close to identity matrix
print("Is close to identity:\n", np.allclose(identity, np.eye(2)))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =\n", AB)
print("BA =\n", BA)
print("AB equals BA?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = (np.dot(A, B)).T
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T =\n", AB_transpose)
print("B^T * A^T =\n", BT_AT)
print("Equality check:", np.allclose(AB_transpose, BT_AT))

A * A^(-1) =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is close to identity:
 True

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB equals BA? False

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Equality check: True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [23]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Right-hand side vector B
B = np.array([-1, -3, 9])

# Solve using inverse method: X = A^(-1) * B
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution [x, y, z]:", X)

Solution [x, y, z]: [ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [24]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Right-hand side vector B
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A_inv with B to get solution X
X = np.dot(A_inv, B)

print("Inverse of A:\n", A_inv)
print("\nSolution [x, y, z]:", X)

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution [x, y, z]: [ 2.  1. -2.]
